language: node_js
node_js:
- '8.11'
branches:
  only:
  - 1.0
before_install:
- npm i -g npm@6
before_script:
- npm i -g @angular/cli
cache:
  directories:
  - node_modules
script:
- npm run-script build
before_deploy:
- cd dist/socket
deploy:
  provider: npm
  email: don.carron@gmail.com,
  skip_cleanup: true
  on:
    branch: 1.0
  api_key:
    secure: js+5zp5hD5C2ZDgk9VJaAzQY5mkfQMwq9d0XmUIgZGOVKDC+zktny6YdS75OM5kPTYKV6lJqdcy4BOvaKikqBUsnhSz01vmI4fvQ/tYNyi4VzUE/noMtteVYHQRV73gM7XJTeDMFTCohsoiGHPydH20rHFPIKsJKer6B4XGMjcKw5R/X5dSfswozGaaW256vBv3EisyQ5P52Ne+ccp3Ox94y6tdJbRlA0zLlcUwwoojUVfeF28ANhHjsVZSnvi9ddgpGv4abVhTh4L/4mvYyHmN5VlsPmVqj3kK6JfVAhsvbOUhCl22Mn2cH5Doa7olegnlZb9IryokI2fTVkcphFFXJyvkJwGTp83rdAaHic1CfvHtDTUFFjr/RpciWP/jq8+1eea6322fy/xMI6zBtfR39/D3URjVuTyCi7W5KVzgMkRJNcldINQwA3idqXIt3NalnaJ/0THOL0MMoxQkhKCEmWkbu9nbKFopI3vBw2aGkWcyybqO/ZnixANL3rsSXScbxdAkwWecyyn4JebiZ8J2q3V7XCFGu2kpGbOP7sWpUiFoaVi/KXVFLB2j8zYqxto4emNRD+6z5FBuo1U3IjFV5JX7uwqg1P1sYIVewjln4zzsEFduupNvD1g8/r5UnDmpsXaT8CbYsYtN/53iLt70Tzrd8T0zHOQksKHsTczU=
notifications:
  email:
    on_failure: change
    on_success: change
