language: node_js
node_js:
- '8.11'
branches:
  only:
  - 1.0
before_install:
- npm i -g npm@6
before_script:
- npm i -g @angular/cli
cache:
  directories:
  - node_modules
script:
- npm run-script build
before_deploy:
- cd dist\socket
deploy:
  provider: npm
  email: don.carron@gmail.com,
  skip_cleanup: true
  on:
    branch: 1.0
  api_key:
    secure: aw0x8jmfbnjB/xoAvKXsnKfX4AAvmol/KlEIItRhixQiPcioUPMxlW1fhAQvVcMMp7Et4Os2WxWZdvBxwJDbf8Pqul/O422i589uTBsVn1CG44k1l3Af/tT614FR50vW4K075lMN2HNqcwXCDY7Pn+cStiBqugLA6waN8WIkScP2CigS542Z+unYEDiQauS+klvwOIdMGZEtbeSCr1nxrHZK8tHLyF8q8VK1+ETqZa2uYfUp/JSxif5N5a6knA7Et+s66qo4Z+ZWy41thw7moxGDY9kpnH6BkQ7yceCOjybxov2v5WHWQJqYUSl3jVSMLlmzA0sQIe/Opc8/YgtHSK/3h0Te1nPUsBJH4kPvDzZnI36az9B9dZRcqX5nGzvoupaBSVMxTI5D7xSBol/on2Bgu9kFkgq6yDXlnPc5dL5FCfkmmgNpLUdeUT+qefuYJq0SbCBQGLq7rOny7gGFY2Wswf0cUJcG0fQwvTFt5YYT1xe3hnRWBRGQ1G8pQHSUaiu6Jdu2y+0+clEcjgQ1ZAxnkloI7DFC7yG4FxADVl3zMKRXqM+2ilUGbF1+By4dFxcnxwkpjD9zr1jH+E83Hev5NzT4GeBd7h6umDGaXr2xFZ43rTDaisum1MkFkBMYnYQV7Hy1aDOUe1dGOldXJOTUgys35C7f3k59FiH3JCo=
notifications:
  email:
    on_failure: change
    on_success: change